#!/usr/bin/env python3
"""Generate C++ header with embedded file contents as byte arrays.

Usage: embed_resource.py <output> [--compress] <varname1>=<file1> ...

Outputs a header with:
  inline constexpr unsigned char kVarName[] = { 0x00, ... };
  inline constexpr size_t kVarNameSize = 123;

With --compress, each resource is gzipped instead and paired with its original size:
  inline constexpr unsigned char kVarNameGz[] = { 0x1f, ... };
  inline constexpr gz_resource kVarName{ kVarNameGz, 45, 123 };
Compressed headers pull in envy's util.h for gz_resource and util_inflate_resource.
"""

import argparse
import struct
import sys
import zlib
from pathlib import Path

# Fixed 10-byte gzip header: deflate, no flags, mtime 0, max compression, unknown OS. Built
# by hand rather than via gzip.compress so output is byte-identical on every build host.
GZIP_HEADER = b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff"


def gzip_bytes(data: bytes) -> bytes:
    """Deterministically wrap raw deflate output in a gzip container."""
    deflate = zlib.compressobj(9, zlib.DEFLATED, -zlib.MAX_WBITS)
    body = deflate.compress(data) + deflate.flush()
    trailer = struct.pack("<II", zlib.crc32(data) & 0xFFFFFFFF, len(data) & 0xFFFFFFFF)
    return GZIP_HEADER + body + trailer


def to_pascal_case(name: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(word.capitalize() for word in name.split("_"))


def format_bytes(data: bytes) -> str:
    """Format bytes as C++ array initializer."""
    lines = []
    line = ""
    for i, b in enumerate(data):
        chunk = f"0x{b:02x}"
        if i < len(data) - 1:
            chunk += ", "
        if len(line) + len(chunk) > 90:
            lines.append(line)
            line = chunk
        else:
            line += chunk
    if line:
        lines.append(line)
    return "\n    ".join(lines)


def generate_resource(varname: str, data: bytes, compress: bool) -> str:
    pascal = to_pascal_case(varname)
    if not compress:
        return f"""inline constexpr unsigned char k{pascal}[] = {{
    {format_bytes(data)}
}};
inline constexpr size_t k{pascal}Size = {len(data)};
"""

    gz = gzip_bytes(data)
    if zlib.decompress(gz, 16 + zlib.MAX_WBITS) != data:
        raise RuntimeError(f"gzip round-trip mismatch for '{varname}'")
    return f"""inline constexpr unsigned char k{pascal}Gz[] = {{
    {format_bytes(gz)}
}};
inline constexpr gz_resource k{pascal}{{ k{pascal}Gz, {len(gz)}, {len(data)} }};
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed files as C++ byte arrays")
    parser.add_argument("output", help="Output header path")
    parser.add_argument(
        "resources",
        nargs="+",
        metavar="VAR=FILE",
        help="Variable name and file path pairs",
    )
    parser.add_argument(
        "--compress",
        action="store_true",
        help="Gzip each resource; emit a gz_resource instead of a raw byte array",
    )
    parser.add_argument(
        "--normalize-eol",
        action="store_true",
        help="Normalize CR/CRLF line endings to LF in all resources",
    )
    parser.add_argument(
        "-D",
        dest="defines",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="Text substitution: replace @@KEY@@ with VALUE in resource content",
    )
    args = parser.parse_args()

    output_path = Path(args.output)

    # Parse --define pairs
    substitutions: dict[bytes, bytes] = {}
    for d in args.defines:
        if "=" not in d:
            print(f"Error: invalid define '{d}', expected KEY=VALUE", file=sys.stderr)
            return 1
        key, value = d.split("=", 1)
        substitutions[f"@@{key}@@".encode()] = value.encode()

    # Parse var=file pairs
    resources = []
    for res in args.resources:
        if "=" not in res:
            print(
                f"Error: invalid resource format '{res}', expected VAR=FILE",
                file=sys.stderr,
            )
            return 1
        varname, filepath = res.split("=", 1)
        resources.append((varname, Path(filepath)))

    # Generate header
    header_parts = [
        "// Auto-generated by embed_resource.py - DO NOT EDIT",
        "#pragma once",
        "",
        '#include "util.h"' if args.compress else "#include <cstddef>",
        "",
        "namespace envy::embedded {",
        "",
    ]

    for varname, filepath in resources:
        if not filepath.exists():
            print(f"Error: file not found: {filepath}", file=sys.stderr)
            return 1

        data = filepath.read_bytes()
        if args.normalize_eol:
            data = data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        for pattern, replacement in substitutions.items():
            data = data.replace(pattern, replacement)
        header_parts.append(generate_resource(varname, data, args.compress))

    header_parts.append("}  // namespace envy::embedded")
    header_parts.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(header_parts))

    return 0


if __name__ == "__main__":
    sys.exit(main())
